# Assignment: Nano Project ANP001: Write a Playbook to Deploy a Static HTML Site
---
  - name: deploy multiple static websites on ubuntuserver
    hosts: ubuntuserver
    become: true
    tasks:
      - name: make sure nginx is installed
        ansible.builtin.package:
          name: nginx
          state: present

      - name: create directory for  website1
        ansible.builtin.file:
          path: /var/www/html/site1
          state: directory
          mode: '0755'
      - name: create directory for website2
        ansible.builtin.file:
          path: /var/www/html/site2
          state: directory
          mode: '0755'
      - name: copy first website  in relevant dir
        ansible.builtin.copy:
          src: ./files/site1
          dest: /var/www/html/
          mode: '0755'
      # - name: copy second website  in relevant dir
      #   ansible.builtin.copy:
      #     src: ./files/site2
      #     dest: /var/www/html/
      #     mode: '0755'
    
      - name: create nginx config file 
        ansible.builtin.copy:
          dest: "/etc/nginx/sites-available/site1"
          content: |
            server {
              listen 80;
              server_name site1.local;
              root /var/www/html/site1;
              index index.html;
            }
      - name: create nginx config file2 
        ansible.builtin.copy:
          dest: "/etc/nginx/sites-available/site2"
          content: |
            server {
              listen 80;
              server_name site2.local;
              root /var/www/html/site2;
              index index.html;
            }

      - name: enable site1 by creating symlink
        ansible.builtin.file:
          src: "/etc/nginx/sites-available/site1"
          dest: "/etc/nginx/sites-enabled/site1"
          state: link
      - name: enable site2 by creating symlink
        ansible.builtin.file:
          src: "/etc/nginx/sites-available/site2"
          dest: "/etc/nginx/sites-enabled/site2"
          state: link

      - name: remove default if exist
        ansible.builtin.file:
          path: /etc/nginx/sites-available/default
          state: absent

      - name: Remove default nginx site if exists
        ansible.builtin.file:
          path: /etc/nginx/sites-enabled/default
          state: absent

      - name: Test nginx configuration
        ansible.builtin.command: nginx -t
        register: nginx_test
        ignore_errors: yes

      - name: Print nginx config test output
        ansible.builtin.debug:
          var: nginx_test.stdout_lines

      - name: Reload nginx
        ansible.builtin.service:
          name: nginx
          state: reloaded
