# deploy  portfolio on ubuntuserver afte cloning from github 
---
  - name: deploy portfolio website on ubuntuserver on nginx after cloning from github
    hosts: ubuntuserver
    become: true
    tasks:
      - name: ensure nginx is installed
        ansible.builtin.package:
          name: nginx
          state: present
      - name: ensure target dir exist which is /var/www/html/site2
        ansible.builtin.file:
          path: /var/www/html/site2
          state: directory
          mode: '0755'

      - name: clone github repo in relevant dir(/var/www/html/site2)
        ansible.builtin.git:
          repo: 'https://github.com/asadbashir7755/asadbashir-portfolio.com.git'
          dest: /var/www/html/site2
          clone: yes
          update: yes
      - name: create nginx config file
        ansible.builtin.copy:
          dest: /etc/nginx/sites-available/site2
          content: |
            server {
              listen 80;
              server_name site2.local;
              root /var/www/html/site2;
              index index.html;
            }

      - name: enable site2 by creating symlink
        ansible.builtin.file:
          src: /etc/nginx/sites-available/site2
          dest: /etc/nginx/sites-enabled/site2
          state: link
      - name: remove default site if exist in sites_available
        ansible.builtin.file:
          path: /etc/nginx/sites-available/default
          state: absent
        
      - name: remove default site if exist in sites_enabled
        ansible.builtin.file:
          path: /etc/nginx/sites_enabled/default
          state: absent
      
      - name: Test nginx configuration
        ansible.builtin.command: nginx -t
        register: nginx_test
        ignore_errors: yes

      - name: Print nginx config test output
        ansible.builtin.debug:
          var: nginx_test.stdout_lines

      - name: Reload nginx
        ansible.builtin.service:
          name: nginx
          state: reloaded
      
