users:
  - name: asad
    comment: "asad bashir "
    group: asad
    groups: "asad,bilawal"
    create_home: yes
    append: yes
  - name: bilawal
    comment: "bilawal ali faiz"
    group: bilawal
    groups: "bilawal,asad"
    create_home: yes
    append: yes
  - name: sheryar
    comment: "sheryar ahsen qamar"
    group: sheryar
    create_home: yes
    append: no
