
- name: Check if project directory is already marked as safe
  ansible.builtin.command: git config --global --get-all safe.directory
  register: git_safe_dirs
  changed_when: false

- name: Mark project directory as safe for Git
  ansible.builtin.command: git config --global --add safe.directory {{ website_path }}
  become: yes
  when: website_path not in git_safe_dirs.stdout_lines


- name: Clone or update repo
  ansible.builtin.git:
    repo: "{{ website_repo }}"
    dest: "{{ website_path }}"
    clone: yes          # ensures clone if folder is empty
    update: yes         # updates if repo already exists
    force: no           # overwrites local changes if needed
  ignore_errors: yes    
  register: git_result


- name: Debug Git result
  ansible.builtin.debug:
    var: git_result
- block:
    - name: Set permissions
      ansible.builtin.file:
        path: "{{ website_path }}"
        owner: "{{ website_owner }}"
        group: "{{ website_group }}"
        mode: '0755'
        recurse: yes

    - name: Deploy PHP DB config files
      ansible.builtin.template:
        src: db.php.j2
        dest: "{{ item }}"
        owner: "{{ website_owner }}"
        group: "{{ website_group }}"
        mode: '0644'
      loop: "{{ config_paths }}"

    - name: Import SQL dump from app repo
      shell: mysql -u{{ db_user }} -p{{ db_pass }} {{ db_name }} < {{ db_dumpfile_path }}
      become: true
      notify: restart apache

  when: git_result.changed


