- name: check nginx
  ansible.builtin.command: nginx -v
  register: nginx_check
  ignore_errors: yes

- name: print what nginx task is running
  ansible.builtin.debug:
    var: nginx_check
- name: install git on server
  ansible.builtin.package:
    name: git
    state: latest
  register: git_result

- name: print what git task is returning whole output
  ansible.builtin.debug:
    var: git_result

- name: print what git task is returning just return code
  ansible.builtin.debug:
    var: git_result.rc

# just for example
# - name: Deploy nginx config
#   ansible.builtin.template:
#     src: site.j2
#     dest: /etc/nginx/conf.d/site.conf
#   register: config_change

# - name: Restart nginx if config changed
#   ansible.builtin.service:
#     name: nginx
#     state: restarted
#   when: config_change.changed
