---
  - name: Comment out only the exact 'Listen 80' line if not already commented
    ansible.builtin.replace:
      path: /etc/apache2/ports.conf
      regexp: '^(?<!#)Listen 80$'
      replace: '#Listen 80'

  - name: add port no in apache config file
    ansible.builtin.lineinfile:
      path: /etc/apache2/ports.conf
      line: "Listen {{apache_listening_port}}"
      state: present
      insertafter: "^Listen 80"


  - name: update vhosts file so that apache listen on that port
    ansible.builtin.replace:
      path: /etc/apache2/sites-enabled/000-default.conf
      regexp: "<VirtualHost \\*:80>"
      replace: "<VirtualHost *:{{apache_listening_port}}>"
    notify: restart apache

  - name: create document root for all websites
    ansible.builtin.file:
      path: "{{ item.doc_root}}/{{item.name}}"
      state: directory
    loop: "{{ websites }}"

  - name: create  apache config file  for each websites
    ansible.builtin.template:
      src: vhosts.conf.j2
      dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
      owner: root
      group: root
      mode: '0644'
    loop: "{{ websites }}"
    notify: restart apache

  - name: Enable virtual hosts
    ansible.builtin.file:
      src: "/etc/apache2/sites-available/{{ item.name }}.conf"
      dest: "/etc/apache2/sites-enabled/{{ item.name }}.conf"
      state: link
    loop: "{{ websites }}"
    notify: restart apache
    
