---
- name: Setup MySQL Server for ELMS App
  hosts: db_servers
  become: yes
  vars_files:
      ../vault_1.0_staging/vault.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: geerlingguy.mysql
